# datasource configuration
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
    token:
      header: Authorization
mp:
  jwt:
    verify:
      issuer: https://example.com/issuer
      publickey:
        location: publicKey.pem

quarkus:
  native:
    resources:
      includes: publicKey.pem
  datasource:
    db-kind:  mysql
    username: root
    password: Root123456
    reactive:
      url: mysql://localhost:3306/quarkus_demo
    devservices:
      enabled: false
      username: root
      password: Root123456
      db-name: quarkus_demo
      port: 33906
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
  http:
    port: 8090
    auth:
      permission:
        bearer:
          paths: /**
          policy: authenticated
          auth-mechanism: bearer
      proactive: false
